import { Card, EmptyState, FormField, Header, Loader } from "@/components";
import { randomPrompt } from "@/utils";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [loading, setLoading] = useState<boolean>(false);
  const [allPosts, setAllPosts] = useState([]);
  const [searchText, setSearchText] = useState<string>('');

  return (
    <>
      <Head>
        <title>DALL.E</title>
      </Head>

      <Header />

      <main className="px-4 py-8 sm:p-8 w-full bg-[#f9fafe] min-h-[calc(100vh-73px)]">
        <section className="w-full max-w-7xl mx-auto">
          <div>
            <h1 className="font-extrabold text-[#222328] text-3xl">
              The Community Showcase
            </h1>
            <p className="mt-2 text-[#666e75] text-base max-w-lg">
              Browse through a collection of imaginative and visually stunning
              images generated by DALL-E AI.
            </p>
          </div>

          <div className="mt-10">
            <FormField />
          </div>

          <div className="mt-10">
            {loading ? (
              <div className="flex justify-center items-center">
                <Loader />
              </div>
            ) : (
              <>
                {searchText && (
                  <h2 className="font-medium text-[#666e75] text-lg mb-3">
                    Showing results for:{" "}
                    <span className="text-[#222328]">{searchText}</span>
                  </h2>
                )}

                {searchText ? (
                  <div className="grid grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 gap-3">
                    {allPosts.map((post: any) => (
                      <Card key={post._id} {...post} />
                    ))}
                  </div>
                ) : (
                  <EmptyState
                    title="No results found"
                    subtitle="Try searching for something else"
                  />
                )}
              </>
            )}
          </div>
        </section>
      </main>
    </>
  );
}
